# Generated by Django 5.0.6 on 2024-07-01 04:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cars_car_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car_shop',
            name='Seats',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.AlterField(
            model_name='car_shop',
            name='Suitcase',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
