# Generated by Django 5.0.6 on 2024-07-01 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_car_shop_seats_alter_car_shop_suitcase'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Komanda',
            new_name='Komanda_img',
        ),
        migrations.RenameModel(
            old_name='car_shop',
            new_name='mashin_shop',
        ),
        migrations.RenameModel(
            old_name='model',
            new_name='modeli',
        ),
    ]
