# Generated by Django 5.0.6 on 2024-07-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_komanda_komanda_img_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='biz_haqmizda',
            new_name='biz_haqmizda_ga',
        ),
        migrations.RenameModel(
            old_name='bizning_asosiy_qoydlarmiz',
            new_name='bizning_asosiy_qoydlar',
        ),
    ]
