# Generated by Django 5.0.6 on 2024-07-02 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_rename_car_shop_car_car_sh'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car_details',
            name='additional_images',
        ),
        migrations.AddField(
            model_name='vehicleimage',
            name='car_d',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='car_a', to='main.car_details'),
            preserve_default=False,
        ),
    ]
