# Generated by Django 5.0.6 on 2024-07-02 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_car_details_additional_images_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleimage',
            old_name='car_d',
            new_name='car_a',
        ),
    ]
