# Generated by Django 5.0.6 on 2024-07-02 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_rename_car_d_vehicleimage_car_a'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Galereya_logo',
        ),
        migrations.DeleteModel(
            name='Galerya_model',
        ),
        migrations.DeleteModel(
            name='Galerya_turlar',
        ),
    ]
