# Generated by Django 5.0.6 on 2024-07-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_delete_galereya_logo_delete_galerya_model_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='mashin_yuish_uchun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateField()),
                ('message', models.TextField()),
            ],
        ),
    ]
