# Generated by Django 5.0.6 on 2024-07-05 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=16)),
                ('holder', models.CharField(max_length=100)),
                ('expiration_month', models.CharField(max_length=2)),
                ('expiration_year', models.CharField(max_length=4)),
                ('ccv', models.CharField(max_length=3)),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='country',
            field=models.CharField(choices=[('RU', 'Rossiya'), ('UZ', "O'ZBEKISTON")], default='UZ', max_length=200),
        ),
    ]
