# Generated by Django 5.0.6 on 2024-07-05 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_creditcard_alter_address_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='cart',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='main.creditcard'),
            preserve_default=False,
        ),
    ]
