# Generated by Django 5.0.6 on 2024-07-07 08:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_mashin_yuish_uchun_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mashin_yuish_uchun',
            name='user',
        ),
    ]
