# Generated by Django 5.0.6 on 2024-07-07 08:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_remove_mashin_yuish_uchun_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashin_yuish_uchun',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
