# Generated by Django 5.0.6 on 2024-07-07 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_mashin_yuish_uchun_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='mashin_yuish_uchun',
            name='mobile_no',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
