# Generated by Django 5.0.6 on 2024-07-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_mashin_yuish_uchun_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mashin_yuish_uchun',
            name='mobile_no',
            field=models.CharField(max_length=20),
        ),
    ]
