# Generated by Django 5.0.6 on 2024-07-07 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_alter_mashin_yuish_uchun_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_month',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_year',
            field=models.CharField(max_length=4),
        ),
    ]
