# Generated by Django 5.0.6 on 2024-07-07 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_alter_creditcard_expiration_month_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='cart',
        ),
    ]
