# Generated by Django 5.0.6 on 2024-07-07 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_address_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='car_det',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_det', to='main.car_details'),
        ),
    ]
